fix: convert image to base64 data: before upload
BitteProtocol/meme.cooking-bitte-agent pull request #4
Opened 2024-12-11 16:02 UTC by sainthiago

2024-12-11 16:32 UTC, Markeljan requested changes
A LOT of requested changes that are out of scope but this file needs some TLC.  

Main issues:
- remove nested try catch,
- move static functions & variables outside of the GET request.
- Add NextResponse return type

2024-12-11 16:32 UTC, Markeljan commented on src/app/api/create-meme/route.ts
> +import { Buffer } from "buffer";
NIT: use `node:buffer` https://biomejs.dev/linter/rules/use-nodejs-import-protocol

2024-12-11 16:32 UTC, Markeljan commented on src/app/api/create-meme/route.ts
>  export async function GET(request: Request) {
This should be a NextRequest type.  Also this should always return a NextResponse with an error object rather than throwing.

2024-12-11 16:32 UTC, Markeljan commented on src/app/api/create-meme/route.ts
> +      try {
Already in a `trycatch` just throw the error

2024-12-11 16:32 UTC, Markeljan commented on src/app/api/create-meme/route.ts
> +    const dataUriToBlob = (dataUri: string): Blob => {
These static functions should not be declared in the GET request.  Same for all of the constant values.

2024-12-11 16:32 UTC, Markeljan commented on src/app/api/create-meme/route.ts
>      console.log("Generated transaction payload:", transactionPayload);
remove console.log

2024-12-11 16:32 UTC, Markeljan commented on src/app/api/create-meme/route.ts
>      const errorMessage =
use `errorString()` util function

2024-12-11 16:32 UTC, Markeljan commented on src/app/api/create-meme/route.ts
>      console.error("Error generating meme creation transaction payload:", error);
2 error logs in this catch statement

2025-01-06 14:14 UTC, Markeljan approved these changes

2025-01-06 14:16 UTC, sainthiago reviewed
LGTM @rubenmarcus

2025-01-07 15:30 UTC, merged